###################################################################################
!/bin/bash
###################################################################################
##################### Author : Archna Joshi #######################################
###################################################################################
---
# Basic provisioning example
- name: Install Webserver 
  hosts: ec2server 
  sudo: yes

  tasks:
   - name: install apache 
     apt: name=apache2 state=installed update_cache=yes

   - name: restart apache
     service: name=apache2 state=restarted

   - name: Copying default welcome page
     copy: src=HelloAnsible.html dest=/var/www/html/HelloAnsible.html 
