# Created by - Prachi Patel
- name: Terminate instances
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
      - name: Terminate instances that were previously launched
        local_action: ec2 state='absent' instance_ids= region=us-west-2

